train_file: ['data/train_formatted.json']
             
test_file: ['data/val_formatted.json']
# answer_list: 'data/answer_list.json'
vqa_dict: 'data/vqa_dict.json'


vqa_root: 'data/' #train2014/

image_res: 384
batch_size_train: 8
batch_size_test: 4
k_test: 128

alpha: 0.4
distill: False
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-6, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}